# Generated by Django 3.1.4 on 2020-12-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0022_auto_20201222_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
