# Generated by Django 3.1.4 on 2020-12-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_auto_20201223_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdetails',
            name='worker_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
